spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BlogUjjwal
spring.datasource.username=root
spring.datasource.password=Ujjwal365#$
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect